### ISSUE TITLE
Could not parse JSON in file 

### ISSUE THREAD

**Issue by mavjt** [mtrutledge/generator-dnn#72]
## Describe the bug
I get an error when trying to create a SPA module.  I'm new to yeoman so followed the steps in your tutorial to get everything installed correctly.  Then I created an MVC module which worked perfectly.
Then I went to create an SPA one and it failed after entering the last setting field.

## To Reproduce
Create new folder, go to folder and run yo dnn.
After entering all details (see screenshot) I get the error below.

## Screenshots
![Screenshot 2019-05-15 12 29 01](https://user-images.githubusercontent.com/4969271/57740727-5bcdb980-770d-11e9-91e4-bec10493236b.png)

## Errors
Error: Could not parse JSON in file: C:\node\dnnyeoman\test2\Test2\package.json. Detail: Unexpected token i in JSON at position 135
    at EditionInterface.module.exports [as readJSON] (C:\node\dnnyeoman\node_modules\mem-fs-editor\lib\actions\read-json.js:8:13)
    at EditionInterface.module.exports [as extendJSON] (C:\node\dnnyeoman\node_modules\mem-fs-editor\lib\actions\extend-json.js:6:30)
    at module.exports.writing (C:\node\dnnyeoman\node_modules\generator-dnn\generators\spa\index.js:304:13)
    at Object.<anonymous> (C:\node\dnnyeoman\node_modules\yeoman-generator\lib\index.js:424:27)
    at C:\node\dnnyeoman\node_modules\run-async\index.js:25:25
    at new Promise (<anonymous>)
    at C:\node\dnnyeoman\node_modules\run-async\index.js:24:19
    at self.env.runLoop.add.completed (C:\node\dnnyeoman\node_modules\yeoman-generator\lib\index.js:425:13)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
Emitted 'error' event at:
    at Immediate.setImmediate (C:\node\dnnyeoman\node_modules\yeoman-generator\lib\index.js:433:22)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)

I'm runing on Win10 from a node.js command line. 
Immediatly after I tried to create a Persona Bar module and that worked fine too.

**Comment by mtrutledge** [comment]
I will take a look at this.
